services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=Dating-site
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:root/dating_site"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: